'use strict';
// Official Blender films. Preserve credits and the project-specific license terms.
window.R1_DEFAULT_MOVIES = [
  {
    "id": "sintel",
    "title": "Sintel",
    "year": 2010,
    "duration": 15,
    "genre": "Fantasy",
    "language": "English",
    "description": "A young traveler searches for a lost dragon, following their unlikely friendship into a world of snow, danger and discovery.",
    "video": "https://www.youtube.com/watch?v=eRsGyueVLvQ",
    "poster": "assets/sintel.webp",
    "backdrop": "assets/sintel-hero.webp",
    "credit": "© 2010 Blender Foundation / Blender Studio",
    "license": "CC BY 3.0",
    "source": "https://studio.blender.org/projects/sintel/",
    "licenseUrl": "https://creativecommons.org/licenses/by/3.0/",
    "featured": true,
    "added": 1791216000000
  },
  {
    "id": "wing-it",
    "title": "Wing It!",
    "year": 2023,
    "duration": 4,
    "genre": "Comedy",
    "language": "No dialogue",
    "description": "An engineer and an enthusiastic would-be pilot are thrown together aboard a space shuttle they can barely control.",
    "video": "https://www.youtube.com/watch?v=u9lj-c29dxI",
    "poster": "assets/wing-it.webp",
    "backdrop": "assets/wing-it.webp",
    "credit": "© 2023 Blender Foundation / Blender Studio",
    "license": "CC BY 4.0",
    "source": "https://studio.blender.org/projects/wing-it/",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0/",
    "featured": false,
    "added": 1791215999999
  },
  {
    "id": "charge",
    "title": "Charge",
    "year": 2022,
    "duration": 4,
    "genre": "Sci-Fi",
    "language": "No dialogue",
    "description": "An old man breaks into a battery factory in a world short of energy, only to face a relentless security machine.",
    "video": "https://www.youtube.com/watch?v=UXqq0ZvbOnk",
    "poster": "assets/charge.webp",
    "backdrop": "assets/charge.webp",
    "credit": "© 2022 Blender Foundation / Blender Studio",
    "license": "CC BY 4.0",
    "source": "https://studio.blender.org/projects/charge/",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0/",
    "featured": false,
    "added": 1791215999998
  },
  {
    "id": "sprite-fright",
    "title": "Sprite Fright",
    "year": 2021,
    "duration": 11,
    "genre": "Horror",
    "language": "English",
    "description": "A forest trip takes a gruesomely funny turn when a group of teenagers crosses paths with tiny mushroom creatures. Contains animated horror and violence.",
    "video": "https://www.youtube.com/watch?v=_cMxraX_5RE",
    "poster": "assets/sprite-fright.webp",
    "backdrop": "assets/sprite-fright.webp",
    "credit": "© 2021 Blender Foundation / Blender Studio",
    "license": "CC BY (see creator terms)",
    "source": "https://studio.blender.org/projects/sprite-fright/",
    "licenseUrl": "https://studio.blender.org/projects/sprite-fright/pages/about/",
    "featured": false,
    "added": 1791215999997
  },
  {
    "id": "spring",
    "title": "Spring",
    "year": 2019,
    "duration": 8,
    "genre": "Fantasy",
    "language": "No dialogue",
    "description": "A shepherd girl and her dog enter a mist-covered forest to awaken ancient spirits and bring the seasons back into balance.",
    "video": "https://www.youtube.com/watch?v=WhWc3b3KhnY",
    "poster": "assets/spring.webp",
    "backdrop": "assets/spring.webp",
    "credit": "© 2019 Blender Foundation / Blender Studio",
    "license": "CC BY 4.0",
    "source": "https://studio.blender.org/projects/spring/",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0/",
    "featured": false,
    "added": 1791215999996
  },
  {
    "id": "agent-327",
    "title": "Agent 327: Operation Barbershop",
    "year": 2017,
    "duration": 4,
    "genre": "Action",
    "language": "English",
    "description": "An undercover agent visits a suspicious barbershop, where a routine investigation quickly becomes a close shave. A short proof-of-concept film.",
    "video": "https://www.youtube.com/watch?v=mN0zPOpADL4",
    "poster": "assets/icon.svg",
    "backdrop": "assets/icon.svg",
    "credit": "© 2017 Blender Foundation; original comics © Martin Lodewijk",
    "license": "CC BY-ND (see creator terms)",
    "source": "https://studio.blender.org/projects/agent-327/",
    "licenseUrl": "https://studio.blender.org/projects/agent-327/pages/about/",
    "featured": false,
    "added": 1791215999995
  },
  {
    "id": "tears-of-steel",
    "title": "Tears of Steel",
    "year": 2012,
    "duration": 12,
    "genre": "Sci-Fi",
    "language": "English",
    "description": "In a future Amsterdam, a team of scientists and fighters revisits a painful memory in a last attempt to save the world.",
    "video": "https://www.youtube.com/watch?v=R6MlUcmOul8",
    "poster": "assets/tears-of-steel.webp",
    "backdrop": "assets/tears-of-steel.webp",
    "credit": "© 2012 Blender Foundation / Blender Studio",
    "license": "CC BY 3.0",
    "source": "https://studio.blender.org/projects/tears-of-steel/",
    "licenseUrl": "https://creativecommons.org/licenses/by/3.0/",
    "featured": false,
    "added": 1791215999994
  },
  {
    "id": "big-buck-bunny",
    "title": "Big Buck Bunny",
    "year": 2008,
    "duration": 11,
    "genre": "Animation",
    "language": "No dialogue",
    "description": "A gentle giant of a rabbit has had enough of three mischievous forest bullies. A playful woodland battle of wits begins.",
    "video": "https://www.youtube.com/watch?v=aqz-KE-bpKQ",
    "poster": "assets/big-buck-bunny.webp",
    "backdrop": "assets/big-buck-bunny.webp",
    "credit": "© 2008 Blender Foundation / Blender Studio",
    "license": "CC BY 3.0",
    "source": "https://studio.blender.org/projects/big-buck-bunny/",
    "licenseUrl": "https://creativecommons.org/licenses/by/3.0/",
    "featured": false,
    "added": 1791215999993
  }
];
